### ISSUE TITLE
Header glitch/bump

### ISSUE THREAD

**Issue by thek1d21** [creativetimofficial/ct-argon-design-system-pro#10]
Hey there, great theme.
The header (possibly headroom.js) has  a glitch/bump when scrolling down. It happens mainly at 1st attempt to scroll whn page its loaded/refresehd.
I first saw it on a website im building and then i checked at creative-tim and the demo there has  the same issue.
Tried, chrome - ff - safari - brave and i was able to reproduce the issues on all of them.
Also, the overall scroll gets glitchy as well sometimes. 
https://drive.google.com/file/d/1I4dIaImE1fuqJlETk4lW6GPvhtvCAjY3/view?usp=sharing
Thanks

**Comment by thek1d21** [comment]
Changing navbar-main from absolute to fixed seems like an fix for me, although u guys should definitely check it out as im next to a brick in css skills :D

.navbar.navbar-main {
  width: 100%;
  position: absolute;
   }

.navbar.navbar-main {
  width: 100%;
  position: fixed;
  z-index: 99; }

**Comment by rarestoma** [comment]
Hi @thek1d21,

Thank you for working with our products and for helping us fix this issue. You can also add 'position-fixed' on 'navbar-main' class and it will work fine.

All the best,
Rares

**Comment by thek1d21** [comment]
Thank you.
