### ISSUE TITLE
Flash of unstyled content

### ISSUE THREAD

**Issue by illmatic** [creativetimofficial/ct-argon-design-system-pro#9]
### Version
Argon Desing System Pro - v1.0.0
### Reproduction link
https://ritualshare.com/
### Operating System
Linux
### Device
Desktop
### Browser & Version
Chrome - latest
### Steps to reproduce
go to https://ritualshare.com/ and see
### What is expected?
content is styled when the page loads
### What is actually happening?
I'm noticing a flicker of text before the styling is applied

---

**Comment by rarestoma** [comment]
Hi @illmatic ,

Thank you for working with our products.

I see that you added style, title and metas in the body tag. You have to move them in the head tag and it should work fine.

Please let me know if it works now.

All the best,
Rares

**Comment by illmatic** [comment]
oh my, missed a blade closing directive. Thanks for the spot! Works as
expected now.
